# -*- coding: utf-8 -*-
"""1-3 Interação com usuário.ipyb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vsMS-N0DBttMC8m8i_9-naAlWTaLfsla

#Vizualização de Variáreis e textos
"""

print('conhecendo o comando Print')

x = 8
print(x)

y = 10
soma = x + y
print(soma)

nome = 'Rodrigo Reboucas'
print(nome)

"""Concatenação"""

x = 5
print('O valor de x é', x)

print('O valor de x é', x, 'e o dobro ', x * 2)

print('Eu', nome, 'tirei' , x, 'na prova de Python')

y = 10; z = 20 + x - y
print('Declarar várias variaveis na mesma linha', y, z)

"""Type"""

x = 10
type(x)
print('x', type(x))

nome = 'jhonatan'
print('nome', type(nome))

num = '100'
num_convert = int(num)  #Converter variável
print('num', type (num))
print('num_conver', type (num_convert))

num_float = float (num)
print('num_float', num_float)

"""Imput


*   Armazenar a informação de digitada pelo usuário em uma variável
*   O dado armazenamento sempre será um texto



"""

nome = input("Digite o nome do usuário") # Aguarda o usuário digitar algo
print(name)

valor = input('Digite a nota')
print(nome, 'sua nota foi', valor)

Valor = input('Digite o valor do produto')
print(valor)

desconto = valor - 5

valor_convert = int(valor)
desconto = valor + 5
print (desconto)

desconto - int(valor + 5 )
print(desconto)